name: Jose Sanchez
markdown: kramdown

author:
  name: "Jose Sanchez"
  bio: "PhD student in Robotic Manipulation of Deformable Objects"
  location: "Clermont-Ferrand, France"
  links
    - label "GitHub"
      icon "fab fa-fw fa-github"
      # url: "jsanch2s"
  googlescholar: "https://scholar.google.com/citations?user=ubB7qwgAAAAJ&hl=en"
  email: "jose.sanchez.loza@gmail.com"
  github: "jsanch2s"
  stackoverflow: "https://stackoverflow.com/users/4788274/jos%c3%a9-s%c3%a1nchez?tab=profile"

plugins:
  - jekyll-sitemap
